name: ema_crossover_signal_test
strategy: EmaCrossoverSignalStrategy

rebalance_frequency: ME
position_sizer: equal_weight
timing_config:
  mode: signal_based
  scan_frequency: D
  min_holding_period: 1
train_window_months: 36
test_window_months: 12
universe_config:
  type: named
  universe_name: nasdaq_top20
optimization_targets:
- name: Sortino
  direction: maximize
optimization_constraints:
- metric: Ann. Vol
  max_value: 0.2
optimize:
- parameter: fast_ema_days
  min_value: 7
  max_value: 32
  step: 1
- parameter: slow_ema_days
  min_value: 64
  max_value: 128
  step: 32
- parameter: leverage
  min_value: 1.0
  max_value: 2.0
  step: 0.5
# Risk Management Optimization Parameters
- parameter: stop_loss_atr_multiple
  min_value: 1.5
  max_value: 3.0
  step: 0.25
- parameter: take_profit_atr_multiple
  min_value: 2.0
  max_value: 4.0
  step: 0.5
strategy_params:
  fast_ema_days: 20
  slow_ema_days: 64
  leverage: 1.0
  
  # ATR-based Stop Loss Configuration
  stop_loss_config:
    type: "AtrBasedStopLoss"
    atr_length: 14
    atr_multiple: 2.0
    
  # ATR-based Take Profit Configuration  
  take_profit_config:
    type: "AtrBasedTakeProfit"
    atr_length: 14
    atr_multiple: 3.0
mc_simulations: 100
mc_years: 5
