# Example configuration showing all advanced crossover operators
# This file demonstrates how to use each of the advanced crossover operators

# Example 1: Simulated Binary Crossover (SBX)
name: ga_sbx_example
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 12
optimization_metric: Sharpe
genetic_algorithm_params:
  ga_num_generations: 10
  ga_sol_per_pop: 10
  ga_num_parents_mating: 5
  # SBX parameters
  advanced_crossover_type: simulated_binary
  sbx_distribution_index: 15.0  # Controls how close offspring are to parents
optimize:
- parameter: lookback_months
  type: int
  min_value: 3
  max_value: 12
  step: 1
- parameter: num_holdings
  type: int
  min_value: 10
  max_value: 30
  step: 1
strategy_params:
  long_only: true
  top_decile_fraction: 0.2
  smoothing_lambda: 0.5
  leverage: 1.0
  sma_filter_window: null
