name: momentum_unfiltered
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_targets:
- name: Sortino
  direction: maximize
- name: Max Drawdown
  direction: minimize
optimization_constraints:
- metric: Ann. Vol
  max_value: 0.25
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 35
  step: 1
- parameter: top_decile_fraction
  min_value: 0.05
  max_value: 0.3
  step: 0.01
- parameter: lookback_months
  min_value: 3
  max_value: 14
  step: 1
- parameter: smoothing_lambda
  min_value: 0.0
  max_value: 1.0
  step: 0.05
- parameter: leverage
  min_value: 0.1
  max_value: 2.0
  step: 0.1
strategy_params:
  lookback_months: 12
  num_holdings: 10
  top_decile_fraction: 0.1
  long_only: true
  smoothing_lambda: 0.0
  sizer_dvol_window: 12
  target_volatility: 0.1
  sma_filter_window: null
mc_simulations: 1000
mc_years: 10
