name: test_optuna_minimal
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 5
train_window_months: 36
test_window_months: 48
walk_forward_type: randomized
optimization_metric: Sharpe
optimize:
- parameter: lookback_months
  min_value: 2
  max_value: 3
  step: 1
- parameter: num_holdings
  min_value: 3
  max_value: 4
  step: 1
strategy_params:
  long_only: true
  top_decile_fraction: 0.2
  smoothing_lambda: 0.5
  leverage: 1.0
  sma_filter_window: null
mc_simulations: 10
mc_years: 1
