# VAMS Momentum Strategy Configuration
name: vams_momentum_portfolio
strategy: VamsMomentumPortfolioStrategy

rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
universe_config:
  type: named
  universe_name: sp500_top50
optimization_metric: Total Return
optimize:
  - parameter: num_holdings
    min_value: 5
    max_value: 30
    step: 1
  - parameter: lookback_months
    min_value: 3
    max_value: 12
    step: 1
strategy_params:
  num_holdings: 10
  lookback_months: 6
mc_simulations: 1000
mc_years: 10
