name: momentum_beta_sized
strategy: momentum
rebalance_frequency: ME
position_sizer: rolling_beta
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 35
  step: 1
- parameter: top_decile_fraction
  min_value: 0.05
  max_value: 0.3
  step: 0.01
- parameter: lookback_months
  min_value: 3
  max_value: 14
  step: 1
- parameter: smoothing_lambda
  min_value: 0.0
  max_value: 1.0
  step: 0.05
- parameter: leverage
  min_value: 0.1
  max_value: 2.0
  step: 0.1
- parameter: sma_filter_window
  min_value: 2
  max_value: 24
  step: 1
- parameter: derisk_days_under_sma
  min_value: 0
  max_value: 30
  step: 1
- parameter: sizer_beta_window
  min_value: 2
  max_value: 12
  step: 1
strategy_params:
  long_only: true
  sizer_beta_window: 3
mc_simulations: 1000
mc_years: 10
