name: sharpe_momentum_portfolio
strategy: SharpeMomentumPortfolioStrategy

rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
universe_config:
  type: named
  universe_name: sp500_top50
optimization_metric: Sharpe
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: rolling_window
  min_value: 1
  max_value: 6
  step: 1
strategy_params:
  num_holdings: 10            # int per tunables
  rolling_window: 6           # int months
  top_decile_fraction: 0.1    # float
  smoothing_lambda: 0.5       # float
  leverage: 1.0               # float, >= 1.0 default
  trade_longs: true           # bool
  trade_shorts: false         # bool
  sma_filter_window: 20       # int
mc_simulations: 500
mc_years: 20
