name: TLT_long_month_2
strategy: intramonth_seasonal
rebalance_frequency: D
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 12
test_window_months: 12
optimization_targets:
- name: Sortino
  direction: maximize
use_grid_sampler: true
optimize:
- parameter: entry_day
  type: categorical
  values: [-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
- parameter: hold_days
  type: int
  min_value: 3
  max_value: 14
  step: 1
strategy_params:
  direction: long
  long_only: true
  leverage: 1.0
  allowed_months: [2]
universe:
- TLT 