# Pre-commit hooks for portfolio-backtester project
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=100]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-error-summary]
        additional_dependencies: [types-requests]

  - repo: local
    hooks:
      - id: dip-compliance
        name: Check DIP Compliance (SOLID Principle Enforcement)
        entry: python dev/enforce_dip_compliance.py
        language: python
        pass_filenames: false
        always_run: true
        stages: [commit]
        verbose: true
        description: |
          Enforces Dependency Inversion Principle by checking for direct getattr usage.
          All attribute access should go through DIP interfaces for better testability
          and adherence to SOLID principles.

      - id: dip-compliance-staged
        name: Check DIP Compliance on Staged Files Only
        entry: python dev/enforce_dip_compliance.py
        language: python
        files: '\.py$'
        types: [python]
        stages: [commit]
        description: |
          Fast DIP compliance check on only the staged Python files.
          Ensures new code follows the Dependency Inversion Principle.

# Optional: fail_fast stops running hooks after first failure
fail_fast: false

# Optional: default_stages runs on these stages by default
default_stages: [commit]
