[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio-backtester"
version = "0.1.0"
authors = [
  { name="Mateusz Bartczak", email="mateusz@bartczak.me" },
]
description = "A portfolio backtesting tool"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "yfinance",
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "statsmodels",
    "rich",
    "requests",
    "lxml",
    "tqdm",
    "python-edgar",
    "openpyxl",
    "xlrd==2.0.1",
    "pyarrow",
    "optuna>=4.4",
    "pygad>=3.2.0", # Added pygad
    "pandas-datareader",
    "pytest-cov",
    "httpx",
    "PyYAML",
    "setuptools"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "coverage",
    "radon",
    "xenon"
]

[project.urls]
"Homepage" = "https://github.com/matbart/portfolio-backtester"
"Bug Tracker" = "https://github.com/matbart/portfolio-backtester/issues"
