name: sharpe_sized_momentum
strategy: sharpe_momentum
rebalance_frequency: ME
position_sizer: rolling_sharpe
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_metric: Sharpe
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: rolling_window
  min_value: 1
  max_value: 6
  step: 1
- parameter: sizer_sharpe_window
  min_value: 2
  max_value: 12
  step: 1
strategy_params:
  lookback_months: 11
  top_decile_fraction: 0.1
  smoothing_lambda: 0.5
  leverage: 0.5
  long_only: true
  sma_filter_window: null
mc_simulations: 1000
mc_years: 10
