"# End-of-month long configuration for Intramonth Seasonal Strategy
name: intramonth_seasonal_end_of_month
strategy: intramonth_seasonal
strategy_class: IntramonthSeasonalStrategy
rebalance_frequency: M
position_sizer: equal_weight

strategy_params:
  direction: long
  entry_day: -3  # 3 business days before month end
  hold_days: 3
  price_column_asset: Close
  trade_longs: true
  trade_shorts: false
  use_ema_filter: false
  
  # All months
  trade_month_1: true
  trade_month_2: true
  trade_month_3: true
  trade_month_4: true
  trade_month_5: true
  trade_month_6: true
  trade_month_7: true
  trade_month_8: true
  trade_month_9: true
  trade_month_10: true
  trade_month_11: true
  trade_month_12: true

timing_config:
  mode: signal_based
" 