# End-of-month configuration for Intramonth Seasonal Strategy
name: intramonth_seasonal_end_of_month
strategy: intramonth_seasonal
strategy_class: IntramonthSeasonalStrategy
rebalance_frequency: M  # Monthly rebalancing
position_sizer: equal_weight

strategy_params:
  intramonth_seasonal.direction: long
  intramonth_seasonal.entry_day: -1
  intramonth_seasonal.hold_days: 1
  intramonth_seasonal.trade_longs: true
  intramonth_seasonal.trade_shorts: true
  intramonth_seasonal.use_ema_filter: false
  intramonth_seasonal.fast_ema_len: 21
  intramonth_seasonal.slow_ema_multiplier: 2.0
  
  # Allow trading in all months by default
  intramonth_seasonal.trade_month_1: true
  intramonth_seasonal.trade_month_2: true
  intramonth_seasonal.trade_month_3: true
  intramonth_seasonal.trade_month_4: true
  intramonth_seasonal.trade_month_5: true
  intramonth_seasonal.trade_month_6: true
  intramonth_seasonal.trade_month_7: true
  intramonth_seasonal.trade_month_8: true
  intramonth_seasonal.trade_month_9: true
  intramonth_seasonal.trade_month_10: true
  intramonth_seasonal.trade_month_11: true
  intramonth_seasonal.trade_month_12: true

timing_config:
  mode: signal_based
  
mc_simulations: 0  # Disabled by default
