# Month 3 configuration for Intramonth Seasonal Strategy
name: intramonth_seasonal_month_3
strategy: intramonth_seasonal
strategy_class: IntramonthSeasonalStrategy
rebalance_frequency: M  # Monthly rebalancing
position_sizer: equal_weight

strategy_params:
  intramonth_seasonal.direction: long
  intramonth_seasonal.entry_day: 5
  intramonth_seasonal.hold_days: 10
  intramonth_seasonal.trade_longs: true
  intramonth_seasonal.trade_shorts: true
  intramonth_seasonal.use_ema_filter: false
  intramonth_seasonal.fast_ema_len: 21
  intramonth_seasonal.slow_ema_multiplier: 2.0
  
  # Only trade in month 3
  intramonth_seasonal.trade_month_1: false
  intramonth_seasonal.trade_month_2: false
  intramonth_seasonal.trade_month_3: true
  intramonth_seasonal.trade_month_4: false
  intramonth_seasonal.trade_month_5: false
  intramonth_seasonal.trade_month_6: false
  intramonth_seasonal.trade_month_7: false
  intramonth_seasonal.trade_month_8: false
  intramonth_seasonal.trade_month_9: false
  intramonth_seasonal.trade_month_10: false
  intramonth_seasonal.trade_month_11: false
  intramonth_seasonal.trade_month_12: false

timing_config:
  mode: signal_based
  
mc_simulations: 0  # Disabled by default
