# September-only long configuration
name: intramonth_seasonal_september
strategy: intramonth_seasonal
strategy_class: IntramonthSeasonalStrategy
rebalance_frequency: M
position_sizer: equal_weight

strategy_params:
  intramonth_seasonal.direction: long
  intramonth_seasonal.entry_day: 5
  intramonth_seasonal.hold_days: 10
  intramonth_seasonal.trade_longs: true
  intramonth_seasonal.trade_shorts: false
  intramonth_seasonal.use_ema_filter: false
  
  intramonth_seasonal.trade_month_1: false
  intramonth_seasonal.trade_month_2: false
  intramonth_seasonal.trade_month_3: false
  intramonth_seasonal.trade_month_4: false
  intramonth_seasonal.trade_month_5: false
  intramonth_seasonal.trade_month_6: false
  intramonth_seasonal.trade_month_7: false
  intramonth_seasonal.trade_month_8: false
  intramonth_seasonal.trade_month_9: true
  intramonth_seasonal.trade_month_10: false
  intramonth_seasonal.trade_month_11: false
  intramonth_seasonal.trade_month_12: false

timing_config:
  mode: signal_based
