"# March-only long configuration
name: intramonth_seasonal_march
strategy: intramonth_seasonal
strategy_class: IntramonthSeasonalStrategy
rebalance_frequency: M
position_sizer: equal_weight

strategy_params:
  direction: long
  entry_day: 5
  hold_days: 10
  price_column_asset: Close
  trade_longs: true
  trade_shorts: false
  use_ema_filter: false
  
  trade_month_1: false
  trade_month_2: false
  trade_month_3: true
  trade_month_4: false
  trade_month_5: false
  trade_month_6: false
  trade_month_7: false
  trade_month_8: false
  trade_month_9: false
  trade_month_10: false
  trade_month_11: false
  trade_month_12: false

timing_config:
  mode: signal_based
" 