name: intramonth_seasonal_optimization
strategy: intramonth_seasonal
rebalance_frequency: D
position_sizer: equal_weight
train_window_months: 12
test_window_months: 12

# Universe Configuration: Use method-based universe for seasonal strategy
universe_config:
  type: "method"
  method_name: "get_top_weight_sp500_components"
  n_holdings: 30
  exact: false
optimization_targets:
- name: Sortino
  direction: maximize
optimize:
- parameter: entry_day
  type: categorical
  values: [-14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
- parameter: hold_days
  type: int
  min_value: 3
  max_value: 14
  step: 1
- parameter: use_ema_filter
  type: categorical
  choices: [true, false]
- parameter: long_only
  type: categorical
  choices: [true, false]

strategy_params:
  direction: long
  long_only: false
  leverage: 1.0
  use_ema_filter: false
  # Keep trading enabled for all months by default
  trade_month_1: true
  trade_month_2: true
  trade_month_3: true
  trade_month_4: true
  trade_month_5: true
  trade_month_6: true
  trade_month_7: true
  trade_month_8: true
  trade_month_9: true
  trade_month_10: true
  trade_month_11: true
  trade_month_12: true
enable_monte_carlo_during_optimization: false
universe:
- TLT
