name: sortino_momentum
strategy: sortino_momentum
universe:
- AAPL
- MSFT
- GOOGL
- AMZN
- NVDA
- META
- TSLA
- BRK-B
- UNH
- JNJ
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: rolling_window
  min_value: 1
  max_value: 6
  step: 1
strategy_params:
  sortino_momentum.lookback_months: 11
  sortino_momentum.top_decile_fraction: 0.1
  sortino_momentum.smoothing_lambda: 0.5
  sortino_momentum.leverage: 0.5
  sortino_momentum.long_only: true
  sortino_momentum.sma_filter_window: null
  sortino_momentum.target_return: 0.0
mc_simulations: 1000
mc_years: 10
