name: filtered_lagged_momentum_optimization
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: momentum_lookback_standard
  min_value: 3
  max_value: 12
  step: 1
- parameter: momentum_lookback_predictive
  min_value: 3
  max_value: 12
  step: 1
- parameter: blending_lambda
  min_value: 0.1
  max_value: 0.9
  step: 0.1
- parameter: momentum_skip_standard
  min_value: 1
  max_value: 3
  step: 1
- parameter: momentum_skip_predictive
  min_value: 0
  max_value: 2
  step: 1
- parameter: sma_filter_window
  min_value: 10
  max_value: 40
  step: 10
strategy_params:
  long_only: true
mc_simulations: 500
mc_years: 10
