name: filtered_lagged_momentum_no_opt
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
strategy_params:
  momentum_lookback_standard: 6
  momentum_lookback_predictive: 6
  momentum_skip_standard: 0
  momentum_skip_predictive: 0
  blending_lambda: 0.5
  num_holdings: 15
  top_decile_fraction: 0.1
  smoothing_lambda: 0.0
  leverage: 1.0
  long_only: true
  apply_trading_lag: false
mc_simulations: 100
mc_years: 5
