name: filtered_lagged_momentum_test
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 15
  max_value: 25
  step: 5
- parameter: momentum_lookback_standard
  min_value: 6
  max_value: 12
  step: 3
- parameter: momentum_lookback_predictive
  min_value: 6
  max_value: 12
  step: 3
- parameter: blending_lambda
  min_value: 0.2
  max_value: 0.8
  step: 0.3
- parameter: momentum_skip_standard
  min_value: 1
  max_value: 2
  step: 1
- parameter: momentum_skip_predictive
  min_value: 0
  max_value: 1
  step: 1
- parameter: sma_filter_window
  min_value: 20
  max_value: 30
  step: 10
strategy_params:
  long_only: true
mc_simulations: 100
mc_years: 5
