name: filtered_lagged_momentum_simple
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48

# Universe Configuration: Use combined NASDAQ and Dow Jones
universe_config:
  type: "named"
  universe_names:
    - "nasdaq_top20"
    - "dow_jones"
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 20
  step: 5
- parameter: momentum_lookback_standard
  min_value: 6
  max_value: 12
  step: 3
- parameter: momentum_lookback_predictive
  min_value: 6
  max_value: 12
  step: 3
- parameter: leverage
  min_value: 0.5
  max_value: 1.0
  step: 0.25
strategy_params:
  momentum_skip_standard: 0
  momentum_skip_predictive: 0
  blending_lambda: 0.5
  top_decile_fraction: 0.1
  smoothing_lambda: 0.0
  long_only: true
  apply_trading_lag: false
mc_simulations: 100
mc_years: 5
