description: Aggressive Low-Volatility Factor with higher leverage
strategy_class: LowVolatilityFactorStrategy

# Universe Configuration: Use multiple universes for broader coverage
universe_config:
  type: "named"
  universe_names: 
    - "sp500_top50"
    - "nasdaq_top20"
strategy_params:
  volatility_lookback_days: 126
  size_percentile: 50
  vol_percentile_low: 25
  vol_percentile_high: 75
  beta_lookback_months: 24
  beta_min_cap: 0.25
  beta_max_cap: 2.0
  beta_max_low_vol: 1.0
  use_hedged_legs: true
  long_only: false
  account_for_costs: true
  shorting_fee_annual: 0.01
  leverage: 1.5
  smoothing_lambda: 0.3
name: LowVolatilityFactor_Aggressive
