description: Conservative Low-Volatility Factor with tighter volatility bands
strategy_class: LowVolatilityFactorStrategy
strategy_params:
  volatility_lookback_days: 252
  size_percentile: 50
  vol_percentile_low: 20
  vol_percentile_high: 80
  beta_lookback_months: 36
  beta_min_cap: 0.25
  beta_max_cap: 2.0
  beta_max_low_vol: 1.0
  use_hedged_legs: true
  long_only: true
  account_for_costs: true
  shorting_fee_annual: 0.01
  leverage: 0.8
  smoothing_lambda: 0.7
  price_column: Close
name: LowVolatilityFactor_Conservative
