name: categorical_test
strategy: intramonth_seasonal
rebalance_frequency: ME
train_window_months: 36
test_window_months: 48
optimization_metric: Sharpe Ratio
optimization_target:
  name: Sharpe Ratio
  direction: maximize

optimizers:
  genetic:
    ga_num_generations: 2
    ga_sol_per_pop: 5
    ga_num_parents_mating: 2
    optimize:
    - parameter: position_sizer
      type: categorical
      values: ["equal_weight", "rolling_sharpe"]
    - parameter: active_months
      type: multi-categorical
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  optuna:
    n_trials: 10
    optimize:
    - parameter: position_sizer
      type: categorical
      values: ["equal_weight", "rolling_sharpe"]
    - parameter: active_months
      type: multi-categorical
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

strategy_params:
  long_only: true
