name: uvxy_rsi_signal
strategy: UvxyRsiSignalStrategy

rebalance_frequency: ME
position_sizer: equal_weight
timing_config:
  mode: signal_based
  scan_frequency: D
  min_holding_period: 1
train_window_months: 36
test_window_months: 48
universe_config:
  type: named
  universe_name: sp500_top50
optimization_metric: Sharpe
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: rolling_window
  min_value: 1
  max_value: 6
  step: 1
strategy_params:
  rsi_period: 14
  rsi_threshold: 70
mc_simulations: 500
mc_years: 20
