description: Long-Only Low-Volatility Factor (Net Long-Market approach)
strategy_class: LowVolatilityFactorStrategy
strategy_params:
  volatility_lookback_days: 252
  size_percentile: 50
  vol_percentile_low: 30
  vol_percentile_high: 70
  beta_lookback_months: 36
  use_hedged_legs: true
  long_only: true
  account_for_costs: false
  leverage: 1.0
  smoothing_lambda: 0.5
  price_column: Close
name: LowVolatilityFactor_LongOnly
