name: low_volatility_factor
strategy: "low_volatility_factor"
rebalance_frequency: "ME"
position_sizer: "equal_weight"
transaction_costs_bps: 10
train_window_months: 48
test_window_months: 24

# Universe Configuration: Use S&P 500 top 50 companies for this strategy
universe_config:
  type: "named"
  universe_name: "sp500_top50"
optimization_targets:
  - name: "Sortino"
    direction: "maximize"
strategy_params:
  volatility_lookback_days: 252
  vol_percentile_low: 30
  vol_percentile_high: 70
  beta_lookback_months: 36
  beta_min_cap: 0.25
  beta_max_cap: 2.0
  beta_max_low_vol: 1.0
  use_hedged_legs: true
  long_only: false
  account_for_costs: false
  leverage: 1.0
  smoothing_lambda: 0.5
  price_column: "Close"
  rebalance_frequency: "monthly"
  shorting_fee_annual: 0.01
