name: genetic_minimal
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
walk_forward_type: expanding

optimizers:
  genetic:
    optimization_metric: Sharpe
    ga_num_generations: 2
    ga_sol_per_pop: 3
    ga_num_parents_mating: 2
    advanced_crossover_type: multi_point
    num_crossover_points: 4
    optimize:
    - parameter: num_holdings
      min_value: 3
      max_value: 5
      step: 1

strategy_params:
  long_only: true
  lookback_months: 6
  top_decile_fraction: 0.2
  smoothing_lambda: 0.5
  leverage: 1.0
  sma_filter_window: null
