name: genetic_variants
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 12

optimizers:
  genetic_sbx:
    optimization_metric: Sharpe
    ga_num_generations: 10
    ga_sol_per_pop: 10
    ga_num_parents_mating: 5
    advanced_crossover_type: simulated_binary
    sbx_distribution_index: 15.0
    optimize:
    - parameter: lookback_months
      type: int
      min_value: 3
      max_value: 12
      step: 1
    - parameter: num_holdings
      type: int
      min_value: 10
      max_value: 30
      step: 1
  genetic_uniform:
    optimization_metric: Sharpe
    ga_num_generations: 10
    ga_sol_per_pop: 10
    ga_num_parents_mating: 5
    advanced_crossover_type: uniform_variant
    uniform_crossover_bias: 0.3
    optimize:
    - parameter: lookback_months
      type: int
      min_value: 3
      max_value: 12
      step: 1
    - parameter: num_holdings
      type: int
      min_value: 10
      max_value: 30
      step: 1

strategy_params:
  long_only: true
  top_decile_fraction: 0.2
  smoothing_lambda: 0.5
  leverage: 1.0
  sma_filter_window: null
