name: momentum_optimize_sizer
strategy: momentum_dvol_sizer
rebalance_frequency: ME
train_window_months: 36
test_window_months: 48
optimization_metric: Sharpe
optimize:
- parameter: position_sizer
  type: categorical
  values: ["equal_weight", "rolling_sharpe", "rolling_sortino", "rolling_beta", "rolling_benchmark_corr", "rolling_downside_volatility"]
- parameter: num_holdings
  min_value: 15
  max_value: 25
  step: 5
- parameter: sizer_sharpe_window
  min_value: 3
  max_value: 9
  step: 3
- parameter: sizer_sortino_window
  min_value: 3
  max_value: 9
  step: 3
- parameter: sizer_beta_window
  min_value: 3
  max_value: 9
  step: 3
- parameter: sizer_corr_window
  min_value: 3
  max_value: 9
  step: 3
- parameter: sizer_dvol_window
  min_value: 3
  max_value: 9
  step: 3
- parameter: target_volatility
  min_value: 0.05
  max_value: 0.2
  step: 0.05
- parameter: target_return
  min_value: 0.0
  max_value: 0.02
  step: 0.005
strategy_params:
  long_only: true
  lookback_months: 6
  sizer_sharpe_window: 6
  sizer_sortino_window: 6
  sizer_beta_window: 6
  sizer_corr_window: 6
  sizer_dvol_window: 6
  target_volatility: 0.1
  target_return: 0.005
mc_simulations: 50
mc_years: 5
