name: momentum_sma_filtered
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
optimization_metric: Total Return
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: derisk_days_under_sma
  min_value: 1
  max_value: 30
  step: 1
strategy_params:
  lookback_months: 11
  top_decile_fraction: 0.1
  smoothing_lambda: 0.5
  leverage: 0.5
  long_only: true
  sma_filter_window: 10
  derisk_days_under_sma: 10
mc_simulations: 1000
mc_years: 10
