name: momentum_with_multiple_universes
strategy: momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48

# Example: Multiple named universes configuration (union)
universe_config:
  type: "named"
  universe_names: 
    - "nasdaq_top20"
    - "dow_jones"

strategy_params:
  lookback_months: 6
  num_holdings: 20
  top_decile_fraction: 0.1
  smoothing_lambda: 0.0
  leverage: 1.0
  long_only: true
  apply_trading_lag: false

mc_simulations: 100
mc_years: 5