name: calmar_momentum_portfolio
strategy: CalmarMomentumPortfolioStrategy

rebalance_frequency: ME
position_sizer: equal_weight
timing_config:
  mode: time_based
  rebalance_frequency: ME
train_window_months: 36
test_window_months: 48
universe_config:
  type: named
  universe_name: sp500_top50
optimization_metric: Calmar
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: lookback_months
  min_value: 6
  max_value: 18
  step: 1
strategy_params:
  lookback_months: 12
  num_holdings: 10
  top_decile_fraction: 0.1
  smoothing_lambda: 0.5
  leverage: 1.0
  trade_longs: true
  trade_shorts: false
  sma_filter_window: 20
mc_simulations: 500
mc_years: 20
