name: low_volatility_factor
strategy: low_volatility_factor
rebalance_frequency: ME
position_sizer: equal_weight
start_date: '2018-01-01'
end_date: '2023-12-31'
train_window_months: 48
test_window_months: 24
universe_config:
  type: named
  universe_name: sp500_top50
optimization_targets:
- name: Sortino
  direction: maximize
strategy_params:
  low_volatility_factor.volatility_lookback_days: 252
  low_volatility_factor.vol_percentile_low: 30
  low_volatility_factor.vol_percentile_high: 70
  low_volatility_factor.beta_lookback_months: 36
  low_volatility_factor.beta_min_cap: 0.25
  low_volatility_factor.beta_max_cap: 2.0
  low_volatility_factor.beta_max_low_vol: 1.0
  low_volatility_factor.use_hedged_legs: true
  low_volatility_factor.long_only: false
  low_volatility_factor.leverage: 1.0
  low_volatility_factor.smoothing_lambda: 0.5
  low_volatility_factor.price_column: Close
  low_volatility_factor.rebalance_frequency: M
