import pytest
import pandas as pd
import numpy as np
from unittest.mock import MagicMock
from src.portfolio_backtester.risk_management.daily_stop_loss_monitor import DailyStopLossMonitor
from src.portfolio_backtester.risk_management.daily_take_profit_monitor import DailyTakeProfitMonitor
from src.portfolio_backtester.backtesting.position_tracker import Position

# -------------------------------------------------------------------------
# Fixtures
# -------------------------------------------------------------------------

@pytest.fixture
def monitor_sl():
    return DailyStopLossMonitor()

@pytest.fixture
def monitor_tp():
    return DailyTakeProfitMonitor()

@pytest.fixture
def mock_tracker():
    tracker = MagicMock()
    # Position: AAPL, Weight 0.5, Entry 100
    pos1 = Position(ticker="AAPL", weight=0.5, entry_price=100.0, entry_date=pd.Timestamp("2020-01-01"))
    # Position: MSFT, Weight 0.5, Entry 200
    pos2 = Position(ticker="MSFT", weight=0.5, entry_price=200.0, entry_date=pd.Timestamp("2020-01-01"))
    tracker.current_positions = {"AAPL": pos1, "MSFT": pos2}
    return tracker

@pytest.fixture
def mock_handler():
    # Can be used for both SL and TP as interface is similar (calculate_levels, apply_logic)
    handler = MagicMock()
    return handler

# -------------------------------------------------------------------------
# Tests for DailyStopLossMonitor
# -------------------------------------------------------------------------

def test_stop_loss_reset_monitoring_state(monitor_sl):
    monitor_sl.triggered_positions = {"AAPL": pd.Timestamp("2020-01-01")}
    monitor_sl.last_check_date = pd.Timestamp("2020-01-01")
    
    monitor_sl.reset_monitoring_state()
    
    assert not monitor_sl.triggered_positions
    assert monitor_sl.last_check_date is None

def test_stop_loss_simultaneous_triggers(monitor_sl, mock_tracker, mock_handler):
    current_date = pd.Timestamp("2020-01-02")
    current_prices = pd.Series({"AAPL": 90.0, "MSFT": 180.0}) # Both dropped
    
    # Handler returns weights where BOTH are liquidated (0.0)
    mock_handler.apply_stop_loss.return_value = pd.Series(
        {"AAPL": 0.0, "MSFT": 0.0}, index=["AAPL", "MSFT"]
    )
    
    result = monitor_sl.check_positions_for_stop_loss(
        current_date, mock_tracker, current_prices, mock_handler, pd.DataFrame()
    )
    
    # Should contain columns for both, value 0.0
    assert "AAPL" in result.columns
    assert "MSFT" in result.columns
    assert result.loc[current_date, "AAPL"] == 0.0
    assert result.loc[current_date, "MSFT"] == 0.0
    
    assert "AAPL" in monitor_sl.triggered_positions
    assert "MSFT" in monitor_sl.triggered_positions

def test_stop_loss_partial_liquidation_unsupported(monitor_sl, mock_tracker, mock_handler):
    # Monitor logic assumes if weight changes to 0 -> liquidated.
    # What if weight changes from 0.5 to 0.25 (partial stop)?
    # _identify_liquidated_positions checks: is_closed = (weights_after == 0)
    # So partial liquidation is NOT treated as a "trigger" event in the current monitor logic
    # that sets 'triggered_positions'.
    
    current_date = pd.Timestamp("2020-01-02")
    current_prices = pd.Series({"AAPL": 90.0, "MSFT": 200.0})
    
    # AAPL reduced to 0.25
    mock_handler.apply_stop_loss.return_value = pd.Series(
        {"AAPL": 0.25, "MSFT": 0.5}, index=["AAPL", "MSFT"]
    )
    
    result = monitor_sl.check_positions_for_stop_loss(
        current_date, mock_tracker, current_prices, mock_handler, pd.DataFrame()
    )
    
    # Since no position became 0, liquidated_positions should be empty
    # And thus result should be empty (no liquidation signals generated by monitor)
    # The monitor is designed for FULL liquidation signals primarily.
    assert result.empty
    assert "AAPL" not in monitor_sl.triggered_positions

# -------------------------------------------------------------------------
# Tests for DailyTakeProfitMonitor
# -------------------------------------------------------------------------

def test_take_profit_get_monitoring_stats(monitor_tp):
    monitor_tp.triggered_positions = {"AAPL": pd.Timestamp("2020-01-01")}
    monitor_tp.last_check_date = pd.Timestamp("2020-01-01")
    
    stats = monitor_tp.get_monitoring_stats()
    assert stats["total_triggered_positions"] == 1
    assert "AAPL" in stats["triggered_positions"]

def test_take_profit_invalid_tracker(monitor_tp, mock_handler):
    # Pass an object without current_positions
    tracker = "Not a tracker"
    result = monitor_tp.check_positions_for_take_profit(
        pd.Timestamp("2020-01-01"), tracker, pd.Series(), mock_handler, pd.DataFrame()
    )
    assert result.empty

def test_take_profit_no_entry_price(monitor_tp, mock_handler):
    tracker = MagicMock()
    # Position without entry price
    pos = Position(ticker="AAPL", weight=0.5, entry_price=None, entry_date=pd.Timestamp("2020-01-01"))
    tracker.current_positions = {"AAPL": pos}
    
    # Handler should receive NaN for entry price
    mock_handler.calculate_take_profit_levels.return_value = pd.Series({"AAPL": 150.0})
    mock_handler.apply_take_profit.return_value = pd.Series({"AAPL": 0.0}) # Liquidate
    
    current_date = pd.Timestamp("2020-01-02")
    monitor_tp.check_positions_for_take_profit(
        current_date, tracker, pd.Series({"AAPL": 140.0}), mock_handler, pd.DataFrame()
    )
    
    # Verify handler call arguments
    call_args = mock_handler.calculate_take_profit_levels.call_args
    entry_prices_arg = call_args[1]["entry_prices"]
    assert np.isnan(entry_prices_arg["AAPL"])
