name: calmar_momentum
strategy: calmar_momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48

# Universe Configuration: Use Dow Jones for Calmar momentum
universe_config:
  type: "named"
  universe_name: "dow_jones"
optimization_metric: Calmar
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 30
  step: 1
- parameter: rolling_window
  min_value: 1
  max_value: 6
  step: 1
strategy_params:
  lookback_months: 11
  top_decile_fraction: 0.1
  smoothing_lambda: 0.5
  leverage: 0.5
  long_only: true
  sma_filter_window: null
mc_simulations: 500
mc_years: 20
