name: ema_roro_signal
strategy: EmaRoroSignalStrategy

rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 24
test_window_months: 12
universe_config:
  type: named
  universe_name: nasdaq_top20
optimization_targets:
- name: Sortino
  direction: maximize
strategy_params:
  fast_ema_days: 20
  slow_ema_days: 64
  leverage: 1.0
