name: momentum_beta_filtered
strategy: momentum_beta_filtered
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
strategy_params:
  momentum_beta_filtered.lookback_months: 12
  momentum_beta_filtered.long_only: false
  momentum_beta_filtered.beta_lookback_days: 21
  momentum_beta_filtered.num_high_beta_to_exclude: 3
  momentum_beta_filtered.rsi_length: 2
  momentum_beta_filtered.rsi_overbought: 70
  momentum_beta_filtered.short_max_holding_days: 30
mc_simulations: 100
mc_years: 5
