BACKTEST_SCENARIOS:
  - name: "Momentum_Unfiltered"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_targets:
      - name: "Sortino"
        direction: "maximize"
      - name: "Max Drawdown"
        direction: "minimize"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
    strategy_params:
      lookback_months: 12
      num_holdings: 10
      top_decile_fraction: 0.1
      long_only: True
      smoothing_lambda: 0.0 # Disable EWMA signal smoothing
      sizer_dvol_window: 12 # Default value for downside volatility sizer window
      target_volatility: 0.10 # Default value for target volatility
    mc_simulations: 1000
    mc_years: 10

  - name: "FilteredLaggedMomentum_Optimization"
    strategy: "filtered_lagged_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "momentum_lookback_standard"
        min_value: 3
        max_value: 12
        step: 1
      - parameter: "momentum_lookback_predictive"
        min_value: 3
        max_value: 12
        step: 1
      - parameter: "blending_lambda"
        min_value: 0.1
        max_value: 0.9
        step: 0.1
      - parameter: "momentum_skip_standard"
        min_value: 1
        max_value: 3
        step: 1
      - parameter: "momentum_skip_predictive"
        min_value: 0
        max_value: 2
        step: 1
      - parameter: "sma_filter_window"
        min_value: 10
        max_value: 40
        step: 10
    strategy_params:
      long_only: True
    mc_simulations: 500
    mc_years: 10

  - name: "FilteredLaggedMomentum_Test"
    strategy: "filtered_lagged_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 15
        max_value: 25
        step: 5
      - parameter: "momentum_lookback_standard"
        min_value: 6
        max_value: 12
        step: 3
      - parameter: "momentum_lookback_predictive"
        min_value: 6
        max_value: 12
        step: 3
      - parameter: "blending_lambda"
        min_value: 0.2
        max_value: 0.8
        step: 0.3
      - parameter: "momentum_skip_standard"
        min_value: 1
        max_value: 2
        step: 1
      - parameter: "momentum_skip_predictive"
        min_value: 0
        max_value: 1
        step: 1
      - parameter: "sma_filter_window"
        min_value: 20
        max_value: 30
        step: 10
    strategy_params:
      long_only: True
    mc_simulations: 100
    mc_years: 5

  - name: "Momentum_Vol_Targeted_10pct"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    strategy_params:
      lookback_months: 6
      num_holdings: 20
      smoothing_lambda: 0.5
      long_only: True
      volatility_targeting:
        name: "annualized"
        target_annual_vol: 0.10 # Target 10% annualized volatility
        lookback_days: 60       # Use 60 trading days for vol calculation
        max_leverage: 1.5       # Max leverage capped at 1.5x
        min_leverage: 0.5       # Min leverage at 0.5x
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_Beta_Sized"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "rolling_beta"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
      - parameter: "sizer_beta_window"
        min_value: 2
        max_value: 12
        step: 1
    strategy_params:
      long_only: True
      sizer_beta_window: 3
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_DVOL_Sizer"
    strategy: "momentum_dvol_sizer"
    rebalance_frequency: "ME"
    position_sizer: "rolling_downside_volatility"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_metric: "Total Return"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
      - parameter: "sizer_dvol_window"
        min_value: 2
        max_value: 12
        step: 1
      - parameter: "target_volatility"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "sizer_max_leverage" # Add max_leverage to optimization parameters
        min_value: 1.0
        max_value: 3.0
        step: 0.1
    strategy_params:
      long_only: True
      sizer_dvol_window: 12 # Default value for downside volatility sizer window
      target_volatility: 0.10 # Default value for target volatility
      max_leverage: 2.0 # Default value for max_leverage
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_SMA_Filtered"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Total Return"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 1
        max_value: 30
        step: 1
    strategy_params:
      lookback_months: 11
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: 10 # 10-month SMA filter
      derisk_days_under_sma: 10
    mc_simulations: 1000
    mc_years: 10

  - name: "Sharpe_Momentum"
    strategy: "sharpe_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sharpe"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        type: "int"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Sharpe
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10

  - name: "Test_Optuna_Minimal" # For Optuna integration testing
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 5
    # Use very short train/test windows to speed up data processing within optimization loop
    train_window_months: 12 # Minimal realistic training window
    test_window_months: 3  # Minimal realistic test window
    walk_forward_type: "expanding" # Or rolling, ensure data is sufficient
    optimization_metric: "Sharpe" # Single metric for simplicity
    optimize:
      - parameter: "lookback_months"
        min_value: 2 # Small range
        max_value: 3 # Small range
        step: 1
      - parameter: "num_holdings"
        min_value: 3 # Small number of holdings
        max_value: 5 # Small number of holdings
        step: 1
    strategy_params:
      long_only: True
      # Other essential momentum params, keep them fixed or very tight range if optimized
      top_decile_fraction: 0.2 # Fixed
      smoothing_lambda: 0.5    # Fixed
      leverage: 1.0            # Fixed
      sma_filter_window: null  # Keep it simple
    # No mc_simulations for this test scenario to save time

  - name: "Test_Genetic_Minimal" # For Genetic Algorithm integration testing
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 5
    train_window_months: 12
    test_window_months: 3
    walk_forward_type: "expanding"
    optimization_metric: "Sharpe"
    genetic_algorithm_params: # Ensure fast execution for tests
      ga_num_generations: 2
      ga_sol_per_pop: 3
      ga_num_parents_mating: 2
    optimize:
      # - parameter: "lookback_months" # Temporarily disable for GA debugging
      #   min_value: 2
      #   max_value: 3
      #   step: 1
      - parameter: "num_holdings"
        min_value: 3
        max_value: 5
        step: 1
    strategy_params:
      long_only: True
      lookback_months: 6 # Fixed value for lookback_months
      top_decile_fraction: 0.2
      smoothing_lambda: 0.5
      leverage: 1.0
      sma_filter_window: null
    # No mc_simulations

  - name: "Momentum_Optimize_Sizer" # New scenario for testing sizer optimization
    strategy: "momentum"
    rebalance_frequency: "ME"
    # position_sizer: "equal_weight" # Initial sizer, will be overridden by optimizer
    transaction_costs_bps: 10
    train_window_months: 60 # Keep it reasonably long for sizers like rolling_sharpe
    test_window_months: 24
    optimization_metric: "Sharpe" # Single metric for simplicity
    optimize:
      - parameter: "position_sizer" # Optimize the position sizer choice
      # Add other relevant parameters for the momentum strategy if desired
      - parameter: "num_holdings"
        min_value: 15
        max_value: 25
        step: 5
      # - parameter: "lookback_months" # Temporarily fixed to test sizer optimization
      #   min_value: 6
      #   max_value: 12
      #   step: 3
      # Parameters for sizers that might be chosen:
      - parameter: "sizer_sharpe_window" # Used if rolling_sharpe is chosen
        min_value: 3 # months for window
        max_value: 9
        step: 3
      - parameter: "sizer_sortino_window"
        min_value: 3
        max_value: 9
        step: 3
      - parameter: "sizer_beta_window"
        min_value: 3
        max_value: 9
        step: 3
      - parameter: "sizer_corr_window"
        min_value: 3
        max_value: 9
        step: 3
      - parameter: "sizer_dvol_window"
        min_value: 3
        max_value: 9
        step: 3
      - parameter: "target_volatility" # Used by rolling_downside_volatility sizer
        min_value: 0.05
        max_value: 0.20
        step: 0.05
      - parameter: "target_return" # Used by rolling_sortino sizer
        min_value: 0.0
        max_value: 0.02 # monthly target return, e.g. 0 to 2%
        step: 0.005
    strategy_params:
      long_only: True
      lookback_months: 6 # Fixed lookback for this test
      # Default values for sizer params if not optimized or if sizer doesn't use them
      sizer_sharpe_window: 6
      sizer_sortino_window: 6
      sizer_beta_window: 6
      sizer_corr_window: 6
      sizer_dvol_window: 6
      target_volatility: 0.10
      target_return: 0.005
    mc_simulations: 50 # Fewer for faster test, not for real MC
    mc_years: 5

  - name: "VAMS_Downside_Penalized"
    strategy: "vams_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24 # Use a 24-month training window
    test_window_months: 12 # Test on the next 12 months
    optimization_metric: "Sortino"
    strategy_params:
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "lookback_months"
        min_value: 3
        max_value: 24
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.20
        step: 0.05
      - parameter: "smoothing_lambda"
        min_value: 0.1
        max_value: 0.9
        step: 0.1
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "alpha"
        min_value: 0.0
        max_value: 1.0
        step: 0.1

  - name: "VAMS_No_Downside"
    strategy: "vams_no_downside"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24 # Use a 24-month training window
    test_window_months: 12 # Test on the next 12 months
    optimization_metric: "Sortino"
    strategy_params:
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "lookback_months"
        min_value: 6
        max_value: 24
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.20
        step: 0.05
      - parameter: "smoothing_lambda"
        min_value: 0.1
        max_value: 0.9
        step: 0.1
      - parameter: "leverage"
        min_value: 0.1
        max_value: 1.0
        step: 0.1

  - name: "Sortino_Momentum"
    strategy: "sortino_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Sortino
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
      target_return: 0.0  # Target return for Sortino calculation
    mc_simulations: 1000
    mc_years: 10

  - name: "Calmar_Momentum"
    strategy: "calmar_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Calmar"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Calmar
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 500
    mc_years: 20

  - name: "Sharpe_Sized_Momentum"
    strategy: "sharpe_momentum"
    rebalance_frequency: "ME"
    position_sizer: "rolling_sharpe"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sharpe"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
      - parameter: "sizer_sharpe_window"
        min_value: 2
        max_value: 12
        step: 1
    strategy_params:
      lookback_months: 11
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10

  - name: "FilteredLaggedMomentum_Simple"
    strategy: "filtered_lagged_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 20
        step: 5
      - parameter: "momentum_lookback_standard"
        min_value: 6
        max_value: 12
        step: 3
      - parameter: "momentum_lookback_predictive"
        min_value: 6
        max_value: 12
        step: 3
      - parameter: "leverage"
        min_value: 0.5
        max_value: 1.0
        step: 0.25
    strategy_params:
      momentum_skip_standard: 0  # Fixed - not optimized
      momentum_skip_predictive: 0  # Fixed - not optimized
      blending_lambda: 0.5  # Fixed - simple blending
      top_decile_fraction: 0.1
      smoothing_lambda: 0.0  # No smoothing like basic momentum
      long_only: True
      apply_trading_lag: False  # No trading lag
    mc_simulations: 100
    mc_years: 5

  - name: "FilteredLaggedMomentum_NoOpt"
    strategy: "filtered_lagged_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    strategy_params:
      momentum_lookback_standard: 6
      momentum_lookback_predictive: 6
      momentum_skip_standard: 0  # Fixed - not optimized
      momentum_skip_predictive: 0  # Fixed - not optimized
      blending_lambda: 0.5  # Fixed - simple blending
      num_holdings: 15
      top_decile_fraction: 0.1
      smoothing_lambda: 0.0  # No smoothing like basic momentum
      leverage: 1.0
      long_only: True
      apply_trading_lag: False  # No trading lag
    mc_simulations: 100
    mc_years: 5

  - name: "Momentum_Simple"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    strategy_params:
      lookback_months: 6
      num_holdings: 15
      top_decile_fraction: 0.1
      smoothing_lambda: 0.0
      leverage: 1.0
      long_only: True
      apply_trading_lag: False
    mc_simulations: 100
    mc_years: 5
