BACKTEST_SCENARIOS:
  - name: "Momentum_Unfiltered"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_targets:
      - name: "Sortino"
        direction: "maximize"
      - name: "Max Drawdown"
        direction: "minimize"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
    strategy_params:
      long_only: True
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_Vol_Targeted_10pct"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    strategy_params:
      lookback_months: 6
      num_holdings: 20
      smoothing_lambda: 0.5
      long_only: True
      volatility_targeting:
        name: "annualized"
        target_annual_vol: 0.10 # Target 10% annualized volatility
        lookback_days: 60       # Use 60 trading days for vol calculation
        max_leverage: 1.5       # Max leverage capped at 1.5x
        min_leverage: 0.5       # Min leverage at 0.5x
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_Beta_Sized"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "rolling_beta"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
      - parameter: "sizer_beta_window"
        min_value: 2
        max_value: 12
        step: 1
    strategy_params:
      long_only: True
      sizer_beta_window: 3
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_DVOL_Sizer"
    strategy: "momentum_dvol_sizer"
    rebalance_frequency: "ME"
    position_sizer: "rolling_downside_volatility"
    transaction_costs_bps: 10
    train_window_months: 60
    test_window_months: 24
    optimization_metric: "Total Return"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 35
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
      - parameter: "lookback_months"
        min_value: 3
        max_value: 14
        step: 1
      - parameter: "smoothing_lambda"
        min_value: 0.0
        max_value: 1.0
        step: 0.05
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "sma_filter_window"
        min_value: 2
        max_value: 24
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 0
        max_value: 30
        step: 1
      - parameter: "sizer_dvol_window"
        min_value: 2
        max_value: 12
        step: 1
      - parameter: "target_volatility"
        min_value: 0.05
        max_value: 0.3
        step: 0.01
    strategy_params:
      long_only: True
    mc_simulations: 1000
    mc_years: 10

  - name: "Momentum_SMA_Filtered"
    strategy: "momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Total Return"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "derisk_days_under_sma"
        min_value: 1
        max_value: 30
        step: 1
    strategy_params:
      lookback_months: 11
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: 10 # 10-month SMA filter
      derisk_days_under_sma: 10
    mc_simulations: 1000
    mc_years: 10

  - name: "Sharpe_Momentum"
    strategy: "sharpe_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sharpe"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Sharpe
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10

  - name: "VAMS_Downside_Penalized"
    strategy: "vams_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24 # Use a 24-month training window
    test_window_months: 12 # Test on the next 12 months
    optimization_metric: "Sortino"
    strategy_params:
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "lookback_months"
        min_value: 3
        max_value: 24
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.20
        step: 0.05
      - parameter: "smoothing_lambda"
        min_value: 0.1
        max_value: 0.9
        step: 0.1
      - parameter: "leverage"
        min_value: 0.1
        max_value: 2.0
        step: 0.1
      - parameter: "alpha"
        min_value: 0.0
        max_value: 1.0
        step: 0.1

  - name: "VAMS_No_Downside"
    strategy: "vams_no_downside"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24 # Use a 24-month training window
    test_window_months: 12 # Test on the next 12 months
    optimization_metric: "Sortino"
    strategy_params:
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "lookback_months"
        min_value: 6
        max_value: 24
        step: 1
      - parameter: "top_decile_fraction"
        min_value: 0.05
        max_value: 0.20
        step: 0.05
      - parameter: "smoothing_lambda"
        min_value: 0.1
        max_value: 0.9
        step: 0.1
      - parameter: "leverage"
        min_value: 0.1
        max_value: 1.0
        step: 0.1

  - name: "Sortino_Momentum"
    strategy: "sortino_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sortino"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Sortino
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
      target_return: 0.0  # Target return for Sortino calculation
    mc_simulations: 1000
    mc_years: 10

  - name: "Calmar_Momentum"
    strategy: "calmar_momentum"
    rebalance_frequency: "ME"
    position_sizer: "equal_weight"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Calmar"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
    strategy_params:
      lookback_months: 11 # This will be used for mom_look/pred, but based on Calmar
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 500
    mc_years: 20

  - name: "Sharpe_Sized_Momentum"
    strategy: "sharpe_momentum"
    rebalance_frequency: "ME"
    position_sizer: "rolling_sharpe"
    transaction_costs_bps: 10
    train_window_months: 24
    test_window_months: 12
    optimization_metric: "Sharpe"
    optimize:
      - parameter: "num_holdings"
        min_value: 10
        max_value: 30
        step: 1
      - parameter: "rolling_window"
        min_value: 1
        max_value: 6
        step: 1
      - parameter: "sizer_sharpe_window"
        min_value: 2
        max_value: 12
        step: 1
    strategy_params:
      lookback_months: 11
      top_decile_fraction: 0.10
      smoothing_lambda: 0.5
      leverage: 0.50
      long_only: True
      sma_filter_window: null
    mc_simulations: 1000
    mc_years: 10
