name: filtered_lagged_momentum
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48

# Universe Configuration: Use combined NASDAQ and Dow Jones
universe_config:
  type: "named"
  universe_names:
    - "nasdaq_top20"
    - "dow_jones"

optimizers:
  default:
    optimization_metric: Sortino
    optimize:
    - parameter: num_holdings
      min_value: 10
      max_value: 30
      step: 1
    - parameter: momentum_lookback_standard
      min_value: 3
      max_value: 12
      step: 1
    - parameter: momentum_lookback_predictive
      min_value: 3
      max_value: 12
      step: 1
    - parameter: blending_lambda
      min_value: 0.1
      max_value: 0.9
      step: 0.1
    - parameter: momentum_skip_standard
      min_value: 1
      max_value: 3
      step: 1
    - parameter: momentum_skip_predictive
      min_value: 0
      max_value: 2
      step: 1
    - parameter: sma_filter_window
      min_value: 10
      max_value: 40
      step: 10
  simple:
    optimization_metric: Sortino
    optimize:
    - parameter: num_holdings
      min_value: 10
      max_value: 20
      step: 5
    - parameter: momentum_lookback_standard
      min_value: 6
      max_value: 12
      step: 3
    - parameter: momentum_lookback_predictive
      min_value: 6
      max_value: 12
      step: 3
    - parameter: leverage
      min_value: 0.5
      max_value: 1.0
      step: 0.25
  test:
    optimization_metric: Sortino
    optimize:
    - parameter: num_holdings
      min_value: 15
      max_value: 25
      step: 5
    - parameter: momentum_lookback_standard
      min_value: 6
      max_value: 12
      step: 3
    - parameter: momentum_lookback_predictive
      min_value: 6
      max_value: 12
      step: 3
    - parameter: blending_lambda
      min_value: 0.2
      max_value: 0.8
      step: 0.3
    - parameter: momentum_skip_standard
      min_value: 1
      max_value: 2
      step: 1
    - parameter: momentum_skip_predictive
      min_value: 0
      max_value: 1
      step: 1
    - parameter: sma_filter_window
      min_value: 20
      max_value: 30
      step: 10

strategy_params:
  long_only: true
  momentum_skip_standard: 0
  momentum_skip_predictive: 0
  blending_lambda: 0.5
  top_decile_fraction: 0.1
  smoothing_lambda: 0.0
  apply_trading_lag: false

mc_simulations: 100
mc_years: 5
