name: filtered_lagged_momentum
strategy: filtered_lagged_momentum
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
universe_config:
  type: named
  universe_names:
  - nasdaq_top20
  - dow_jones
optimization_targets:
  - name: Sortino
    direction: maximize

optimize:
    - parameter: num_holdings
      min_value: 10
      max_value: 30
      step: 1
    - parameter: momentum_lookback_standard
      min_value: 3
      max_value: 12
      step: 1
    - parameter: momentum_lookback_predictive
      min_value: 3
      max_value: 12
      step: 1
    - parameter: blending_lambda
      min_value: 0.1
      max_value: 0.9
      step: 0.1
    - parameter: momentum_skip_standard
      min_value: 1
      max_value: 3
      step: 1
    - parameter: momentum_skip_predictive
      min_value: 0
      max_value: 2
      step: 1
    - parameter: sma_filter_window
      min_value: 10
      max_value: 40
      step: 10
strategy_params:
  filtered_lagged_momentum.long_only: true
  filtered_lagged_momentum.momentum_skip_standard: 0
  filtered_lagged_momentum.momentum_skip_predictive: 0
  filtered_lagged_momentum.blending_lambda: 0.5
  filtered_lagged_momentum.top_decile_fraction: 0.1
  filtered_lagged_momentum.smoothing_lambda: 0.0
  filtered_lagged_momentum.apply_trading_lag: false
mc_simulations: 100
mc_years: 5
