name: uvxy_rsi_strategy
description: UVXY short strategy based on SPY RSI(2) signals - Daily signal-driven,
  no rebalancing
strategy: uvxy_rsi
rebalance_frequency: D
position_sizer: equal_weight
train_window_months: 12
test_window_months: 12

# Universe Configuration: Use fixed universe for UVXY strategy
universe_config:
  type: "fixed"
  tickers:
    - "UVXY"
    - "VXX"
    - "SVXY"
optimization_targets:
- name: Sharpe
  direction: maximize
optimize:
- parameter: rsi_threshold
  min_value: 20.0
  max_value: 40.0
  step: 2.5
- parameter: rsi_period
  min_value: 2
  max_value: 5
  step: 1
strategy_params:
  uvxy_rsi.rsi_period: 2
  uvxy_rsi.rsi_threshold: 30.0
  uvxy_rsi.price_column_asset: Close
  uvxy_rsi.price_column_benchmark: Close
  uvxy_rsi.long_only: false
  uvxy_rsi.leverage: 1.0
  uvxy_rsi.smoothing_lambda: 0.0
  uvxy_rsi.rebalance_frequency: daily
mc_simulations: 100
mc_years: 3
