# VAMS Momentum Strategy Configuration
name: vams_momentum_strategy
strategy: vams_momentum
rebalance_frequency: ME
position_sizer: momentum_ranking
train_window_months: 36
test_window_months: 48
optimization_metric: Total Return
optimize:
  - parameter: num_holdings
    min_value: 5
    max_value: 30
    step: 1
  - parameter: lookback_months
    min_value: 3
    max_value: 12
    step: 1
strategy_params:
  vams_momentum.num_holdings: 10
  vams_momentum.lookback_months: 6
mc_simulations: 1000
mc_years: 10