name: momentum_unfiltered_atr
strategy: momentum_unfiltered_atr
rebalance_frequency: ME
position_sizer: equal_weight
transaction_costs_bps: 10
train_window_months: 36
test_window_months: 48
optimization_metric: Sortino
optimize:
- parameter: num_holdings
  min_value: 10
  max_value: 20
  step: 5
- parameter: lookback_months
  min_value: 6
  max_value: 12
  step: 3
- parameter: atr_length
  min_value: 10
  max_value: 20
  step: 5
- parameter: atr_multiple
  min_value: 2.0
  max_value: 3.0
  step: 0.5
strategy_params:
  lookback_months: 12
  num_holdings: 15
  top_decile_fraction: 0.1
  long_only: true
  smoothing_lambda: 0.0
  leverage: 1.0
  sma_filter_window: null
  atr_length: 14
  atr_multiple: 2.5
mc_simulations: 1000
mc_years: 10
