name: seasonal_signal_strategy
strategy: SeasonalSignalStrategy

rebalance_frequency: ME
position_sizer: equal_weight
timing_config:
  mode: signal_based
  scan_frequency: D
  min_holding_period: 1
strategy_params: {}