name: "dummy_strategy_default"
strategy: "dummy"
strategy_class: "DummyStrategyForTesting"

# Universe configuration
universe_config:
  type: single_symbol
  ticker: SPY

# Strategy parameters (fixed values)
strategy_params:
  dummy_strategy_for_testing.open_long_prob: 0.1
  dummy_strategy_for_testing.close_long_prob: 0.01
  dummy_strategy_for_testing.dummy_param_1: 10
  dummy_strategy_for_testing.dummy_param_2: 20

# Optimization configuration
optimization_metric: "Calmar"
optimize:
- parameter: open_long_prob
  min_value: 0.05
  max_value: 0.3
  step: 0.01
- parameter: close_long_prob
  min_value: 0.005
  max_value: 0.05
  step: 0.005
- parameter: dummy_param_1
  min_value: 1
  max_value: 50
  step: 1
- parameter: dummy_param_2
  min_value: 5
  max_value: 100
  step: 1
  
# Backtest configuration
backtest_config:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  rebalance_frequency: "daily"