name: simple_meta_strategy
strategy: simple_meta
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
optimization_targets:
  - name: Sharpe
    direction: maximize
optimize: []
strategy_params:
  simple_meta.initial_capital: 1000000
  simple_meta.min_allocation: 0.05
  simple_meta.rebalance_threshold: 0.05
  simple_meta.allocations:
  - strategy_id: momentum
    strategy_class: CalmarMomentumStrategy
    strategy_params:
      calmar_momentum.rolling_window: 6
      calmar_momentum.num_holdings: 10
      calmar_momentum.sma_filter_window: 20
      calmar_momentum.price_column_benchmark: Close
      calmar_momentum.lookback_months: 11
      calmar_momentum.top_decile_fraction: 0.1
      calmar_momentum.smoothing_lambda: 0.5
      calmar_momentum.leverage: 0.5
      calmar_momentum.long_only: true
      calmar_momentum.timing_config:
        mode: time_based
        rebalance_frequency: M
    weight: 0.7
  - strategy_id: seasonal
    strategy_class: IntramonthSeasonalStrategy
    strategy_params:
      intramonth_seasonal.direction: long
      intramonth_seasonal.entry_day: 5
      intramonth_seasonal.hold_days: 10
      intramonth_seasonal.trade_longs: true
      intramonth_seasonal.trade_shorts: false
      intramonth_seasonal.use_ema_filter: false
      intramonth_seasonal.fast_ema_len: 0
      intramonth_seasonal.slow_ema_multiplier: 2.0
      intramonth_seasonal.timing_config:
        mode: signal_based
    weight: 0.3
mc_simulations: 500
mc_years: 20
