name: simple_meta_strategy
strategy: simple_meta_strategy
rebalance_frequency: ME
position_sizer: equal_weight
train_window_months: 36
test_window_months: 48
optimization_targets:
  - name: Sharpe
    direction: maximize
optimize: []
strategy_params:
  initial_capital: 1000000.0
  min_allocation: 0.05
  rebalance_threshold: 0.05
  simple_meta.allocations:
  - strategy_id: momentum
    
    strategy_params:
      rolling_window: 6
      num_holdings: 10
      sma_filter_window: 20
      price_column_benchmark: Close
      lookback_months: 11
      top_decile_fraction: 0.1
      smoothing_lambda: 0.5
      leverage: 0.5
      trade_longs: true
      trade_shorts: false
      calmar_momentum_portfolio.timing_config:
        mode: time_based
        rebalance_frequency: M
    weight: 0.7
  - strategy_id: seasonal
    
    strategy_params:
      direction: long
      entry_day: 5
      hold_days: 10
      trade_longs: true
      trade_shorts: false
      use_ema_filter: false
      fast_ema_len: 0
      slow_ema_multiplier: 2.0
      intramonth_seasonal.timing_config:
        mode: signal_based
    weight: 0.3
mc_simulations: 500
mc_years: 20
