# Example configuration demonstrating allocation_mode usage
# This file shows how to configure capital allocation modes for different scenarios

# Example 1: Reinvestment Mode (Default - Compounding Enabled)
# Use this for realistic trading simulation where profits compound
name: "Momentum_Reinvestment_Example"
strategy: "portfolio_momentum"
allocation_mode: "reinvestment"  # Enable compounding (default)

strategy_params:
  portfolio_momentum.lookback_months: 12
  portfolio_momentum.skip_months: 1
  leverage: 1.0

universe_config:
  type: fixed
  tickers: ["AAPL", "MSFT", "GOOGL", "AMZN"]

timing_config:
  rebalance_frequency: "M"

position_sizer: "equal_weight"

# Transaction costs
transaction_costs_bps: 13  # 13 basis points total cost

---
# Example 2: Fixed Fractional Mode (Compounding Disabled)
# Use this for fair strategy comparison without compounding effects
name: "Momentum_FixedFractional_Example"
strategy: "portfolio_momentum"
allocation_mode: "fixed_fractional"  # Disable compounding

strategy_params:
  portfolio_momentum.lookback_months: 12
  portfolio_momentum.skip_months: 1
  leverage: 1.0

universe_config:
  type: fixed
  tickers: ["AAPL", "MSFT", "GOOGL", "AMZN"]

timing_config:
  rebalance_frequency: "M"

position_sizer: "equal_weight"

transaction_costs_bps: 13

---
# Example 3: Meta Strategy with Allocation Mode
# Shows how allocation mode affects sub-strategy capital allocation
name: "MetaStrategy_Allocation_Example"
strategy: "SimpleMetaStrategy"
allocation_mode: "reinvestment"  # Controls sub-strategy capital allocation

strategy_params:
  allocation_mode: "reinvestment"  # Also pass to strategy params
  allocations:
    - strategy_id: "momentum"
      strategy_class: "SimpleMomentumPortfolioStrategy"
      strategy_params:
        portfolio_momentum.lookback_months: 6
        portfolio_momentum.skip_months: 1
      weight: 0.6
    - strategy_id: "seasonal"
      strategy_class: "SeasonalSignalStrategy"
      strategy_params:
        seasonal_signal.direction: "long"
      weight: 0.4

universe_config:
  type: fixed
  tickers: ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA"]

timing_config:
  rebalance_frequency: "M"

---
# Example 4: Optimization with Allocation Mode as Parameter
# Shows how to optimize allocation mode along with other parameters
name: "Momentum_Optimization_Example"
strategy: "portfolio_momentum"

# Don't set allocation_mode here - let optimization choose
strategy_params:
  portfolio_momentum.lookback_months:
    type: "int"
    low: 6
    high: 18
    step: 1
  portfolio_momentum.skip_months:
    type: "int" 
    low: 1
    high: 3
    step: 1
  allocation_mode:
    type: "categorical"
    values: ["reinvestment", "fixed_fractional"]
  leverage:
    type: "float"
    low: 0.5
    high: 2.0
    step: 0.1

universe_config:
  type: fixed
  tickers: ["AAPL", "MSFT", "GOOGL", "AMZN"]

timing_config:
  rebalance_frequency: "M"

position_sizer: "equal_weight"

# Walk-forward optimization settings
wfo_config:
  train_window_months: 24
  test_window_months: 6
  step_months: 3