# Nested Meta Strategy Example Configuration
# This demonstrates a meta strategy that allocates to other meta strategies

name: "nested_meta_example"
strategy: "simple_meta"
strategy_class: "SimpleMetaStrategy"
rebalance_frequency: "M"
position_sizer: "equal_weight"
train_window_months: 36
test_window_months: 48

optimization_targets:
  - name: "Sharpe"
    direction: "maximize"

optimize: []

strategy_params:
  simple_meta.initial_capital: 2000000  # Starting capital for this meta strategy
  simple_meta.min_allocation: 0.05      # Minimum allocation per strategy (5%)
  simple_meta.rebalance_threshold: 0.05 # Rebalance when allocation drifts by 5%
  
  simple_meta.allocations:
    # 80% allocation to an equity-focused meta strategy
    - strategy_id: "equity_meta"
      strategy_class: "SimpleMetaStrategy"
      strategy_params:
        simple_meta.initial_capital: 1600000  # Will be overridden by parent allocation
        simple_meta.allocations:
          - strategy_id: "momentum"
            strategy_class: "CalmarMomentumStrategy"
            strategy_params:
              calmar_momentum.rolling_window: 6
              calmar_momentum.num_holdings: 10
              calmar_momentum.sma_filter_window: 10
              calmar_momentum.price_column_benchmark: "Close"
              calmar_momentum.timing_config:
                mode: "time_based"
                rebalance_frequency: "M"
            weight: 0.6  # 60% of equity allocation
            
          - strategy_id: "seasonal"
            strategy_class: "IntramonthSeasonalStrategy"
            strategy_params:
              intramonth_seasonal.direction: "long"
              intramonth_seasonal.entry_day: 5
              intramonth_seasonal.hold_days: 10
              intramonth_seasonal.trade_longs: true
              intramonth_seasonal.trade_shorts: false
              intramonth_seasonal.timing_config:
                mode: "signal_based"
            weight: 0.4  # 40% of equity allocation
      weight: 0.8  # 80% of total capital
      
    # 20% allocation to a conservative strategy (placeholder)
    - strategy_id: "conservative"
      strategy_class: "CalmarMomentumStrategy"  # Using as placeholder for conservative strategy
      strategy_params:
        calmar_momentum.rolling_window: 12  # Longer window for more conservative approach
        calmar_momentum.num_holdings: 20    # More diversified
        calmar_momentum.sma_filter_window: 20
        calmar_momentum.price_column_benchmark: "Close"
        calmar_momentum.timing_config:
          mode: "time_based"
          rebalance_frequency: "Q"  # Quarterly rebalancing
      weight: 0.2  # 20% of total capital

# Meta strategies inherit universe from their sub-strategies
