# Nested Meta Strategy Example Configuration
# This demonstrates a meta strategy that allocates to other meta strategies

strategy_class: "SimpleMetaStrategy"
strategy_params:
  initial_capital: 2000000  # Starting capital for this meta strategy
  min_allocation: 0.05      # Minimum allocation per strategy (5%)
  rebalance_threshold: 0.05 # Rebalance when allocation drifts by 5%
  
  allocations:
    # 80% allocation to an equity-focused meta strategy
    - strategy_id: "equity_meta"
      strategy_class: "SimpleMetaStrategy"
      strategy_params:
        initial_capital: 1600000  # Will be overridden by parent allocation
        allocations:
          - strategy_id: "momentum"
            strategy_class: "CalmarMomentumStrategy"
            strategy_params:
              rolling_window: 6
              num_holdings: 10
              sma_filter_window: 10
              price_column_asset: "Close"
              price_column_benchmark: "Close"
              timing_config:
                mode: "time_based"
                rebalance_frequency: "M"
            weight: 0.6  # 60% of equity allocation
            
          - strategy_id: "seasonal"
            strategy_class: "IntramonthSeasonalStrategy"
            strategy_params:
              direction: "long"
              entry_day: 5
              hold_days: 10
              price_column_asset: "Close"
              trade_longs: true
              trade_shorts: false
              timing_config:
                mode: "signal_based"
            weight: 0.4  # 40% of equity allocation
      weight: 0.8  # 80% of total capital
      
    # 20% allocation to a conservative strategy (placeholder)
    - strategy_id: "conservative"
      strategy_class: "CalmarMomentumStrategy"  # Using as placeholder for conservative strategy
      strategy_params:
        rolling_window: 12  # Longer window for more conservative approach
        num_holdings: 20    # More diversified
        sma_filter_window: 20
        price_column_asset: "Close"
        price_column_benchmark: "Close"
        timing_config:
          mode: "time_based"
          rebalance_frequency: "Q"  # Quarterly rebalancing
      weight: 0.2  # 20% of total capital

# Global configuration (would typically be in main config)
universe:
  - "AAPL"
  - "MSFT"
  - "GOOGL"
  - "AMZN"
  - "TSLA"
  - "NVDA"
  - "META"
  - "NFLX"
  - "CRM"
  - "ADBE"

benchmark: "SPY"