# Simple Meta Strategy Example Configuration
# This demonstrates a basic meta strategy that allocates 70% to momentum and 30% to seasonal

name: "simple_meta_example"
strategy: "simple_meta"
strategy_class: "SimpleMetaStrategy"
rebalance_frequency: "M"
position_sizer: "equal_weight"
train_window_months: 36
test_window_months: 48

optimization_targets:
  - name: "Sharpe"
    direction: "maximize"

optimize: []

strategy_params:
  initial_capital: 1000000  # Starting capital for this meta strategy
  min_allocation: 0.05      # Minimum allocation per strategy (5%)
  rebalance_threshold: 0.05 # Rebalance when allocation drifts by 5%
  
  allocations:
    - strategy_id: "momentum"
      strategy_class: "CalmarMomentumStrategy"
      strategy_params:
        rolling_window: 6
        num_holdings: 10
        sma_filter_window: 10
        price_column_asset: "Close"
        price_column_benchmark: "Close"
        timing_config:
          mode: "time_based"
          rebalance_frequency: "M"
      weight: 0.7  # 70% of available capital
      
    - strategy_id: "seasonal"
      strategy_class: "IntramonthSeasonalStrategy"
      strategy_params:
        direction: "long"
        entry_day: 5
        hold_days: 10
        price_column_asset: "Close"
        trade_longs: true
        trade_shorts: false
        timing_config:
          mode: "signal_based"
      weight: 0.3  # 30% of available capital

# Meta strategies inherit universe from their sub-strategies
