name: Type Checking

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Run MyPy on API Stability Module (Strict)
      run: |
        echo "Checking API stability module (must pass)..."
        mypy src/portfolio_backtester/api_stability/
        
    - name: Run MyPy on Critical Modules (Allow Failures)
      run: |
        echo "Checking critical modules (failures allowed for now)..."
        mypy src/portfolio_backtester/core.py || echo "Core module has type errors - needs fixing"
        mypy src/portfolio_backtester/strategies/base_strategy.py || echo "Base strategy has type errors - needs fixing"
        mypy src/portfolio_backtester/timing/custom_timing_registry.py || echo "Timing registry has type errors - needs fixing"
        
    - name: Generate Type Check Report
      run: |
        echo "Generating comprehensive type check report..."
        python check_critical_types.py || true
        
    - name: Check for Type Regressions
      run: |
        echo "Ensuring API stability module remains type-safe..."
        mypy src/portfolio_backtester/api_stability/ --strict
        
  signature-validation:
    runs-on: ubuntu-latest
    needs: type-check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Run Signature Validation Tests
      run: |
        echo "Running signature validation tests..."
        python -m pytest tests/test_api_stability*.py -v || echo "Signature validation tests not yet implemented"